//variaveis
const botao = document.querySelector(".pesquisar");
const selecao = document.querySelector("#genero");
const indicacao = document.querySelector(".containerSugestao");
const listaSugestoes = indicacao.children;
const limpar = document.querySelector(".btn-limpar");
const diretor = document.querySelector("#diretor");
const btnDiretor = document.querySelector(".btn-diretor");
//event listeners
selecao.addEventListener("change", pesquisa);
limpar.addEventListener("click", limpa);
btnDiretor.addEventListener("click", buscaDiretor);

//lista de filmes
const filmes = [
  {
    titulo: "Titanic",
    genero: "romance",
    stream: "Telecine Play",
    ano: 1997,
    pais: "Estados Unidos",
    direcao: "james cameron",
    rating: 10,
  },
  {
    titulo: "Pulp Fiction",
    genero: "suspense",
    stream: "Telecine Play",
    ano: 1994,
    pais: "Estados Unidos",
    direcao: "quentin tarantino",
    rating: 10,
  },
  {
    titulo: "Vingadores: Guerra Infinita",
    genero: "acao",
    stream: "Telecine Play",
    ano: 2018,
    pais: "Estados Unidos",
    direcao: "anthony russo",
    rating: 10,
  },
  {
    titulo: "Bohemian Rhapsody",
    genero: "biografia",
    stream: "Telecine Play",
    ano: 2018,
    pais: "Estados Unidos",
    direcao: "bryan singer",
    rating: 10,
  },
  {
    titulo: "Azul É A Cor Mais Quente",
    genero: "romance",
    stream: "Telecine Play",
    ano: 2013,
    pais: "França",
    direcao: "abdellatif kechiche",
    rating: 10,
  },
  {
    titulo: "La La Land",
    genero: "musical",
    stream: "Telecine Play",
    ano: 2016,
    pais: "Estados Unidos",
    direcao: "damien chazelle",
    rating: 10,
  },
  {
    titulo: "Central Do Brasil",
    genero: "nacional",
    stream: "Telecine Play",
    ano: 1998,
    pais: "Brasil",
    direcao: "walter salles",
    rating: 10,
  },
  {
    titulo: "Batman: O Cavaleiro das Trevas Ressurge",
    genero: "acao",
    stream: "Telecine Play",
    ano: 2012,
    pais: "Estados Unidos",
    direcao: "christopher nolan",
    rating: 10,
  },
  {
    titulo: "Clube Dos Cinco",
    genero: "comedia",
    stream: "Telecine Play",
    ano: 1985,
    pais: "Estados Unidos",
    direcao: "john hughes",
    rating: 10,
  },
  {
    titulo: "Kill Bill - Volume 1",
    genero: "acao",
    stream: "Telecine Play",
    ano: 2003,
    pais: "Estados Unidos",
    direcao: "quentin tarantino",
    rating: 10,
  },
  {
    titulo: "Bastardos Inglórios",
    genero: "acao",
    stream: "Telecine Play",
    ano: 2009,
    pais: "Estados Unidos",
    direcao: "quentin tarantino",
    rating: 10,
  },
  {
    titulo: "O Fabuloso Destino de Amélie Poulain",
    genero: "comedia",
    stream: "Telecine Play",
    ano: 2001,
    pais: "França",
    direcao: "jean-pierre jeunet",
    rating: 10,
  },
  {
    titulo: "12 Anos De Escravidão",
    genero: "drama",
    stream: "Telecine Play",
    ano: 2013,
    pais: "Estados Unidos",
    direcao: "steve mcqueen",
    rating: 10,
  },
  {
    titulo: "Cidade De Deus",
    genero: "nacional",
    stream: "Telecine Play",
    ano: 2002,
    pais: "Brasil",
    direcao: "fernando meirelles",
    rating: 10,
  },
  {
    titulo: "Que Horas Ela Volta?",
    genero: "nacional",
    stream: "Telecine Play",
    ano: 2015,
    pais: "Brasil",
    direcao: "anna muylaert",
    rating: 10,
  },
  {
    titulo: "Velozes E Furiosos",
    genero: "acao",
    stream: "Telecine Play",
    ano: 2001,
    pais: "Estados Unidos",
    direcao: "rob cohen",
    rating: 10,
  },
  {
    titulo: "E.T. - O Extraterrestre",
    genero: "familia",
    stream: "Telecine Play",
    ano: 1982,
    pais: "Estados Unidos",
    direcao: "steven spielberg",
    rating: 10,
  },
  {
    titulo: "As Vantagens De Ser Invisível",
    genero: "drama",
    stream: "Telecine Play",
    ano: 2012,
    pais: "Estados Unidos",
    direcao: "stephen chbosky",
    rating: 10,
  },
  {
    titulo: "Malévola",
    genero: "aventura",
    stream: "Telecine Play",
    ano: 2014,
    pais: "Estados Unidos",
    direcao: "robert stromberg",
    rating: 10,
  },
  {
    titulo: "O Lado Bom Da Vida",
    genero: "romance",
    stream: "Telecine Play",
    ano: 2012,
    pais: "Estados Unidos",
    direcao: "david o. russell",
    rating: 10,
  },
  {
    titulo: "O Ilusionista",
    genero: "suspense",
    stream: "Telecine Play",
    ano: 2006,
    pais: "Estados Unidos",
    direcao: "neil burguer",
    rating: 10,
  },
  {
    titulo: "Invencível (2006)",
    genero: "drama",
    stream: "Telecine Play",
    ano: 2006,
    pais: "Estados Unidos",
    direcao: "ericson core",
    rating: 10,
  },
  {
    titulo: "Tubarão",
    genero: "suspense",
    stream: "Telecine Play",
    ano: 1975,
    pais: "Estados Unidos",
    direcao: "steven spielberg",
    rating: 10,
  },
  {
    titulo: "Tudo Sobre Minha Mãe",
    genero: "drama",
    stream: "Telecine Play",
    ano: 1999,
    pais: "Espanha",
    direcao: "pedro almodóvar",
    rating: 10,
  },
  {
    titulo: "Trumbo: Lista Negra",
    genero: "drama",
    stream: "Telecine Play",
    ano: 2015,
    pais: "Estados Unidos",
    direcao: "jay roach",
    rating: 10,
  },
  {
    titulo: "Mudança de Hábito",
    genero: "comedia",
    stream: "Telecine Play",
    ano: 1992,
    pais: "Estados Unidos",
    direcao: "emile ardolino",
    rating: 10,
  },
  {
    titulo: "Um Lugar Silencioso",
    genero: "terror",
    stream: "Telecine Play",
    ano: 2018,
    pais: "Estados Unidos",
    direcao: "john krasinski",
    rating: 10,
  },
  {
    titulo: "O Homem Da Máscara De Ferro",
    genero: "acao",
    stream: "Telecine Play",
    ano: 1998,
    pais: "Estados Unidos",
    direcao: "randall wallace",
    rating: 10,
  },
  {
    titulo: "Prenda-me Se For Capaz",
    genero: "drama",
    stream: "Telecine Play",
    ano: 2002,
    pais: "Estados Unidos",
    direcao: "steven spielberg",
    rating: 10,
  },
  {
    titulo: "Homem-Aranha",
    genero: "acao",
    stream: "Telecine Play",
    ano: 2002,
    pais: "Estados Unidos",
    direcao: "sam raimi",
    rating: 10,
  },
  {
    titulo: "Harry Potter e a Pedra Filosofal",
    genero: "aventura",
    stream: "Telecine Play",
    ano: 2001,
    pais: "Estados Unidos",
    direcao: "chris columbus",
    rating: 10,
  },
  {
    titulo: "Harry Potter e a Câmara Secreta",
    genero: "aventura",
    stream: "Telecine Play",
    ano: 2002,
    pais: "Estados Unidos",
    direcao: "chris columbus",
    rating: 10,
  },
  {
    titulo: "Homem De Ferro 3",
    genero: "acao",
    stream: "Telecine Play",
    ano: 2013,
    pais: "Estados Unidos",
    direcao: "shane black",
    rating: 10,
  },
  {
    titulo: "Os Pássaros",
    genero: "terror",
    stream: "Telecine Play",
    ano: 1963,
    pais: "Estados Unidos",
    direcao: "alfred hitchcock",
    rating: 10,
  },
  {
    titulo: "Psicose",
    genero: "suspense",
    stream: "Telecine Play",
    ano: 1960,
    pais: "Estados Unidos",
    direcao: "alfred hitchcock",
    rating: 10,
  },
  {
    titulo: "Matrix",
    genero: "acao",
    stream: "Telecine Play",
    ano: 1999,
    pais: "Estados Unidos",
    direcao: "lana wachowski",
    rating: 10,
  },
  {
    titulo: "Mulher-Maravilha",
    genero: "acao",
    stream: "Telecine Play",
    ano: 2017,
    pais: "Estados Unidos",
    direcao: "petty jenkins",
    rating: 10,
  },
  {
    titulo: "A Bela E A Ferra (2017)",
    genero: "romance",
    stream: "Telecine Play",
    ano: 2017,
    pais: "Estados Unidos",
    direcao: "bill condon",
    rating: 10,
  },
  {
    titulo: "O Curioso Caso de Benjamin Button",
    genero: "drama",
    stream: "Telecine Play",
    ano: 2008,
    pais: "Estados Unidos",
    direcao: "david fincher",
    rating: 10,
  },
  {
    titulo: "A Rocha",
    genero: "acao",
    stream: "Telecine Play",
    ano: 1996,
    pais: "Estados Unidos",
    direcao: "michael bay",
    rating: 10,
  },
  {
    titulo: "Armageddon",
    genero: "acao",
    stream: "Telecine Play",
    ano: 1998,
    pais: "Estados Unidos",
    direcao: "michael bay",
    rating: 10,
  },
  {
    titulo: "Harry Potter E O Prisioneiro De Azkaban",
    genero: "aventura",
    stream: "Telecine Play",
    ano: 2004,
    pais: "Estados Unidos",
    direcao: "alfonso cuarón",
    rating: 10,
  },
  {
    titulo: "Roma",
    genero: "drama",
    stream: "Netflix",
    ano: 2018,
    pais: "Mexico",
    direcao: "alfonso cuarón",
    rating: 10,
  },
  {
    titulo: "Harry Potter E O Calice De Fogo",
    genero: "aventura",
    stream: "Telecine Play",
    ano: 2005,
    pais: "Estados Unidos",
    direcao: "mike newell",
    rating: 10,
  },
  {
    titulo: "Até O Limite Da Honra",
    genero: "acao",
    stream: "Telecine Play",
    ano: 1997,
    pais: "Estados Unidos",
    direcao: "ridley scott",
    rating: 10,
  },
  {
    titulo: "Os Infiltrados",
    genero: "drama",
    stream: "Telecine Play",
    ano: 2006,
    pais: "Estados Unidos",
    direcao: "martin scorsese",
    rating: 10,
  },
  {
    titulo: "O Mistério Da Libélula",
    genero: "drama",
    stream: "Telecine Play",
    ano: 2002,
    pais: "Estados Unidos",
    direcao: "tom shadyac",
    rating: 10,
  },
  {
    titulo: "A Mãe Que Balança O Berço",
    genero: "drama",
    stream: "Telecine Play",
    ano: 1992,
    pais: "Estados Unidos",
    direcao: "curtis hanson",
    rating: 10,
  },
  {
    titulo: "Moulin Rouge - Amor Em Vermelho",
    genero: "musical",
    stream: "Telecine Play",
    ano: 2001,
    pais: "Estados Unidos",
    direcao: "baz luhrmann",
    rating: 10,
  },
  {
    titulo: "A Lagoa Azul",
    genero: "romance",
    stream: "Telecine Play",
    ano: 1980,
    pais: "Estados Unidos",
    direcao: "randal kleiser",
    rating: 10,
  },
  {
    titulo: "De Repente 30",
    genero: "comedia",
    stream: "Telecine Play",
    ano: 2004,
    pais: "Estados Unidos",
    direcao: "gary winick",
    rating: 10,
  },
  {
    titulo: "Encontro Marcado (1998)",
    genero: "drama",
    stream: "Telecine Play",
    ano: 1998,
    pais: "Estados Unidos",
    direcao: "martin brest",
    rating: 10,
  },
  {
    titulo: "Um Amor Para Recordar",
    genero: "romance",
    stream: "Telecine Play",
    ano: 2002,
    pais: "Estados Unidos",
    direcao: "adam shankman",
    rating: 10,
  },
  {
    titulo: "Em Ritmo de Fuga",
    genero: "acao",
    stream: "Telecine Play",
    ano: 2017,
    pais: "Estados Unidos",
    direcao: "edgar wright",
    rating: 10,
  },
  {
    titulo: "2001: Uma Odisséia no Espaço",
    genero: "aventura",
    stream: "Telecine Play",
    ano: 1968,
    pais: "Estados Unidos",
    direcao: "stanley kubrick",
    rating: 10,
  },
  {
    titulo: "Ata-Me",
    genero: "drama",
    stream: "Telecine Play",
    ano: 1990,
    pais: "Estados Unidos",
    direcao: "pedro almodóvar",
    rating: 10,
  },
  {
    titulo: "A Lista De Schindler",
    genero: "drama",
    stream: "Telecine Play",
    ano: 1993,
    pais: "Estados Unidos",
    direcao: "steven spielberg",
    rating: 10,
  },
  {
    titulo: "O Grande Hotel Budapeste",
    genero: "comedia",
    stream: "Telecine Play",
    ano: 2014,
    pais: "Estados Unidos",
    direcao: "wes anderson",
    rating: 10,
  },
  {
    titulo: "O Diabo Veste Prada",
    genero: "comedia",
    stream: "Telecine Play",
    ano: 2006,
    pais: "Estados Unidos",
    direcao: "david frankel",
    rating: 10,
  },
  {
    titulo: "Florence: Quem É Essa Mulher?",
    genero: "biografia",
    stream: "Telecine Play",
    ano: 2016,
    pais: "Estados Unidos",
    direcao: "stephen frears",
    rating: 10,
  },
  {
    titulo: "Má Educação",
    genero: "suspense",
    stream: "Telecine Play",
    ano: 2004,
    pais: "Espanha",
    direcao: "pedro almodóvar",
    rating: 10,
  },
  {
    titulo: "Um Peixe Chamado Wanda",
    genero: "comedia",
    stream: "Telecine Play",
    ano: 1988,
    pais: "Estados Unidos",
    direcao: "charles crichton",
    rating: 10,
  },
  {
    titulo: "O Impossível",
    genero: "drama",
    stream: "Telecine Play",
    ano: 2012,
    pais: "Espanha",
    direcao: "juan bayona",
    rating: 10,
  },
  {
    titulo: "O Chamado",
    genero: "terror",
    stream: "Telecine Play",
    ano: 2002,
    pais: "Estados Unidos",
    direcao: "gore verbinski",
    rating: 10,
  },
  {
    titulo: "Infiltrado Na Klan",
    genero: "drama",
    stream: "Telecine Play",
    ano: 2018,
    pais: "Estados Unidos",
    direcao: "spike lee",
    rating: 10,
  },
  {
    titulo: "Me Chama Pelo Seu Nome",
    genero: "drama",
    stream: "Telecine Play",
    ano: 2017,
    pais: "França",
    direcao: "luca guadagnino",
    rating: 10,
  },
  {
    titulo: "It: A Coisa",
    genero: "terror",
    stream: "Telecine Play",
    ano: 2017,
    pais: "Canadá",
    direcao: "andy muschietti",
    rating: 10,
  },
  {
    titulo: "Um Homem De Família",
    genero: "comedia",
    stream: "Telecine Play",
    ano: 2000,
    pais: "Estados Unidos",
    direcao: "brett ratner",
    rating: 10,
  },
  {
    titulo: "Nós",
    genero: "terror",
    stream: "Telecine Play",
    ano: 2019,
    pais: "Estados Unidos",
    direcao: "jordan peele",
    rating: 10,
  },
  {
    titulo: "Sempre Ao Seu Lado",
    genero: "drama",
    stream: "Telecine Play",
    ano: 2009,
    pais: "Estados Unidos",
    direcao: "lasse hallstrom",
    rating: 10,
  },
  {
    titulo: "Orgulho E Preconceito",
    genero: "drama",
    stream: "Telecine Play",
    ano: 2005,
    pais: "Estados Unidos",
    direcao: "joe wright",
    rating: 10,
  },
  {
    titulo: "Blue Jasmine",
    genero: "drama",
    stream: "Telecine Play",
    ano: 2013,
    pais: "Estados Unidos",
    direcao: "woody allen",
    rating: 10,
  },
  {
    titulo: "Manhattan",
    genero: "comedia",
    stream: "Telecine Play",
    ano: 1979,
    pais: "Estados Unidos",
    direcao: "woody allen",
    rating: 10,
  },
  {
    titulo: "Um Dia de Chuva em Nova York",
    genero: "comedia",
    stream: "Telecine Play",
    ano: 2019,
    pais: "Estados Unidos",
    direcao: "woody allen",
    rating: 10,
  },
  {
    titulo: "Noivo Neurótico, Noiva Nervosa",
    genero: "comedia",
    stream: "Telecine Play",
    ano: 1977,
    pais: "Estados Unidos",
    direcao: "woody allen",
    rating: 10,
  },
  {
    titulo: "Roda Gigante",
    genero: "drama",
    stream: "Telecine Play",
    ano: 2017,
    pais: "Estados Unidos",
    direcao: "woody allen",
    rating: 10,
  },
  {
    titulo: "Para Roma Com Amor",
    genero: "romance",
    stream: "Prime Video",
    ano: 2012,
    pais: "Itália",
    direcao: "woody allen",
    rating: 10,
  },
  {
    titulo: "Tudo Pode Dar Certo",
    genero: "comedia",
    stream: "Prime Video",
    ano: 2009,
    pais: "Estados Unidos",
    direcao: "woody allen",
    rating: 10,
  },
  {
    titulo: "Meia-Noite em Paris",
    genero: "romance",
    stream: "Prime Video",
    ano: 2011,
    pais: "França",
    direcao: "woody allen",
    rating: 10,
  },
  {
    titulo: "História de um Casamento",
    genero: "drama",
    stream: "Netflix",
    ano: 2019,
    pais: "Estados Unidos",
    direcao: "noah baumbach",
    rating: 10,
  },
  {
    titulo: "O Irlandês",
    genero: "drama",
    stream: "Netflix",
    ano: 2019,
    pais: "Estados Unidos",
    direcao: "martin scorsese",
    rating: 10,
  },
  {
    titulo: "A Origem",
    genero: "drama",
    stream: "Netflix",
    ano: 2010,
    pais: "Estados Unidos",
    direcao: "christopher nolan",
    rating: 10,
  },
  {
    titulo: "Gênio Indomável",
    genero: "drama",
    stream: "Telecine Play",
    ano: 1997,
    pais: "Estados Unidos",
    direcao: "gus van sant",
    rating: 10,
  },
  {
    titulo: "As Aventuras De Pi",
    genero: "drama",
    stream: "Telecine Play",
    ano: 2012,
    pais: "Estados Unidos",
    direcao: "ang lee",
    rating: 10,
  },
  {
    titulo: "Um Sonho de Liberdade",
    genero: "drama",
    stream: "HBO GO",
    ano: 1994,
    pais: "Estados Unidos",
    direcao: "frank darabont",
    rating: 10,
  },
  {
    titulo: "Sin City - A Cidade Do Pecado",
    genero: "acao",
    stream: "Telecine Play",
    ano: 2005,
    pais: "Estados Unidos",
    direcao: "quentin tarantino",
    rating: 10,
  },
  {
    titulo: "John Wick",
    genero: "acao",
    stream: "Telecine Play",
    ano: 2014,
    pais: "Estados Unidos",
    direcao: "chad stahelski",
    rating: 10,
  },
  {
    titulo: "O Talentoso Ripley",
    genero: "drama",
    stream: "Telecine Play",
    ano: 1999,
    pais: "Estados Unidos",
    direcao: "anthony minghella",
    rating: 10,
  },
  {
    titulo: "O Grande Dragão Branco",
    genero: "acao",
    stream: "Telecine Play",
    ano: 1988,
    pais: "Estados Unidos",
    direcao: "newt arnold",
    rating: 10,
  },
  {
    titulo: "A Favorita",
    genero: "drama",
    stream: "Telecine Play",
    ano: 2018,
    pais: "Estados Unidos",
    direcao: "yorgos lanthimos",
    rating: 10,
  },
  {
    titulo: "12 Homens E Uma Sentença (1997)",
    genero: "drama",
    stream: "Telecine Play",
    ano: 1997,
    pais: "Estados Unidos",
    direcao: "william friedkin",
    rating: 10,
  },
  {
    titulo: "Dunkirk",
    genero: "drama",
    stream: "Telecine Play",
    ano: 2017,
    pais: "Estados Unidos",
    direcao: "christopher nolan",
    rating: 10,
  },
  {
    titulo: "007 - Cassino Royale",
    genero: "acao",
    stream: "Telecine Play",
    ano: 2006,
    pais: "Estados Unidos",
    direcao: "Martin Campbell",
    rating: 10,
  },
  {
    titulo: "007 - Operação Skyfall",
    genero: "acao",
    stream: "Telecine Play",
    ano: 2012,
    pais: "Estados Unidos",
    direcao: "sam mandes",
    rating: 10,
  },
  {
    titulo: "007 - Quantum Of Solace",
    genero: "acao",
    stream: "Telecine Play",
    ano: 2008,
    pais: "Estados Unidos",
    direcao: "marc forster",
    rating: 10,
  },
  {
    titulo: "Bacurau",
    genero: "nacional",
    stream: "Telecine Play",
    ano: 2019,
    pais: "brasil",
    direcao: "kleber mendonça",
    rating: 10,
  },
  {
    titulo: "Deus É Brasileiro",
    genero: "nacional",
    stream: "Prime Video",
    ano: 2003,
    pais: "Brasil",
    direcao: "carlos diegues",
    rating: 10,
  },
  {
    titulo: "O Terminal",
    genero: "comedia",
    stream: "Prime Video",
    ano: 2004,
    pais: "Estados Unidos",
    direcao: "steven spielberg",
    rating: 10,
  },
  {
    titulo: "Coração Valente",
    genero: "acao",
    stream: "Telecine Play",
    ano: 1995,
    pais: "Estados Unidos",
    direcao: "mel gibson",
    rating: 10,
  },
  {
    titulo: "Antes Do Amanhecer",
    genero: "drama",
    stream: "Telecine Play",
    ano: 1995,
    pais: "Estados Unidos",
    direcao: "richard linklater",
    rating: 10,
  },
  {
    titulo: "Quero Ser John Malkovich",
    genero: "comedia",
    stream: "Telecine Play",
    ano: 1999,
    pais: "Estados Unidos",
    direcao: "spike jonze",
    rating: 10,
  },
  {
    titulo: "Guerra Fria",
    genero: "drama",
    stream: "Telecine Play",
    ano: 2018,
    pais: "França",
    direcao: "pawel pawlikowski",
    rating: 10,
  },
  {
    titulo: "A Onda (2008)",
    genero: "drama",
    stream: "Telecine Play",
    ano: 2008,
    pais: "Alemanha",
    direcao: "dennis gansel",
    rating: 10,
  },
  {
    titulo: "O Último Rei Da Esócia",
    genero: "biografia",
    stream: "Telecine Play",
    ano: 2006,
    pais: "Reino Unido",
    direcao: "kevin macdonald",
    rating: 10,
  },
  {
    titulo: "Flashdance",
    genero: "drama",
    stream: "Telecine Play",
    ano: 1983,
    pais: "Estados Unidos",
    direcao: "adrian lyne",
    rating: 10,
  },
  {
    titulo: "Aquarius",
    genero: "nacional",
    stream: "Telecine Play",
    ano: 2016,
    pais: "Brasil",
    direcao: "kleber mendonça",
    rating: 10,
  },
  {
    titulo: "O Senhor dos Anéis: A Sociedade do Anel",
    genero: "aventura",
    stream: "Telecine Play",
    ano: 2001,
    pais: "Nova Zelândia",
    direcao: "Peter Jackson",
    rating: 10,
  },
  {
    titulo: "Carrie, A Estranha",
    genero: "terror",
    stream: "Telecine Play",
    ano: 1976,
    pais: "Estados Unidos",
    direcao: "brian de palma",
    rating: 10,
  },
  {
    titulo: "O Guarda-Costas (1992)",
    genero: "acao",
    stream: "Telecine Play",
    ano: 1992,
    pais: "Estados Unidos",
    direcao: "mick jackson",
    rating: 10,
  },
  {
    titulo: "Ex-Machina: Instinto Artificial",
    genero: "drama",
    stream: "Telecine Play",
    ano: 2015,
    pais: "Estados Unidos",
    direcao: "alex garland",
    rating: 10,
  },
  {
    titulo: "Xeque-Mate",
    genero: "suspense",
    stream: "Telecine Play",
    ano: 2006,
    pais: "Estados Unidos",
    direcao: "paul mcguigan",
    rating: 10,
  },
  {
    titulo: "Boyhood: Da Infância À Juventude",
    genero: "drama",
    stream: "Telecine Play",
    ano: 2014,
    pais: "Estados Unidos",
    direcao: "richard linklater",
    rating: 10,
  },
  {
    titulo: "A Era Do Gelo",
    genero: "animacao",
    stream: "Telecine Play",
    ano: 2002,
    pais: "Estados Unidos",
    direcao: "carlos saldanha",
    rating: 10,
  },
  {
    titulo: "Esqueceram De Mim",
    genero: "comedia",
    stream: "Telecine Play",
    ano: 1990,
    pais: "Estados Unidos",
    direcao: "chris columbus",
    rating: 10,
  },
  {
    titulo: "O Feitiço De Àquila",
    genero: "aventura",
    stream: "Telecine Play",
    ano: 1985,
    pais: "Estados Unidos",
    direcao: "richard donner",
    rating: 10,
  },
  {
    titulo: "Joias Brutas",
    genero: "drama",
    stream: "Netflix",
    ano: 2020,
    pais: "Estados Unidos",
    direcao: "josh safdie",
    rating: 10,
  },
  {
    titulo: "Sully - O Herói Do Rio Hudson",
    genero: "drama",
    stream: "Netflix",
    ano: 2016,
    pais: "Estados Unidos",
    direcao: "clint eastwood",
    rating: 10,
  },
  {
    titulo: "Gladiador",
    genero: "acao",
    stream: "Netflix",
    ano: 2000,
    pais: "Estados Unidos",
    direcao: "ridley scott",
    rating: 10,
  },
  {
    titulo: "O Voo",
    genero: "drama",
    stream: "netflix",
    ano: 2012,
    pais: "Estados Unidos",
    direcao: "robert zemeckis",
    rating: 10,
  },
  {
    titulo: "Até O Último Homem",
    genero: "drama",
    stream: "Netflix",
    ano: 2016,
    pais: "Estados Unidos",
    direcao: "mel gibson",
    rating: 10,
  },
  {
    titulo: "Forrest Gump",
    genero: "drama",
    stream: "Netflix",
    ano: 1994,
    pais: "Estados Unidos",
    direcao: "robert zemeckis",
    rating: 10,
  },
  {
    titulo: "O Regresso",
    genero: "aventura",
    stream: "Netflix",
    ano: 2015,
    pais: "Estados Unidos",
    direcao: "alejandro g. iñarritu",
    rating: 10,
  },
  {
    titulo: "À Procura Da Felicidade",
    genero: "biografia",
    stream: "Netflix",
    ano: 2006,
    pais: "Estados Unidos",
    direcao: "gabriele muccino",
    rating: 10,
  },
  {
    titulo: "Lion - Uma Jornada Para Casa",
    genero: "biografia",
    stream: "Netflix",
    ano: 2016,
    pais: "Estados Unidos",
    direcao: "garth davis",
    rating: 10,
  },
  {
    titulo: "Clube da Luta",
    genero: "drama",
    stream: "Prime Video",
    ano: 1999,
    pais: "Estados Unidos",
    direcao: "david fincher",
    rating: 10,
  },
  {
    titulo: "Kill Bill: Volume 2",
    genero: "acao",
    stream: "Prime Video",
    ano: 2004,
    pais: "Estados Unidos",
    direcao: "quentin tarantino",
    rating: 10,
  },
  {
    titulo: "O Poderoso Chefão",
    genero: "drama",
    stream: "Prime Video",
    ano: 1972,
    pais: "Estados Unidos",
    direcao: "francis ford coppola",
    rating: 10,
  },
  {
    titulo: "O Poderoso Chefão Parte 2",
    genero: "drama",
    stream: "Prime Video",
    ano: 1974,
    pais: "Estados Unidos",
    direcao: "francis ford coppola",
    rating: 10,
  },
  {
    titulo: "O Poderoso Chefão Parte 3",
    genero: "drama",
    stream: "Prime Video",
    ano: 1990,
    pais: "Estados Unidos",
    direcao: "francis ford coppola",
    rating: 10,
  },
  {
    titulo: "Fogo Contra Fogo (1995)",
    genero: "drama",
    stream: "Prime Video",
    ano: 1995,
    pais: "Estados Unidos",
    direcao: "michael mann",
    rating: 10,
  },
  {
    titulo: "memento",
    genero: "suspense",
    stream: "Prime Video",
    ano: 2001,
    pais: "Estados Unidos",
    direcao: "christopher nolan",
    rating: 10,
  },
];

//funcoes

function pesquisa() {
  const generoSelecao = selecao.value;

  filmes.forEach(function (filme) {
    if (filme.genero == generoSelecao) {
      const sugestao = document.createElement("p");
      sugestao.innerText = filme.titulo + " - Disponível em: " + filme.stream;
      sugestao.classList.add("sugestoes");
      indicacao.appendChild(sugestao);
      limpar.style.display = "block";
    }
  });
}

function limpa() {
  for (var i = listaSugestoes.length - 1; i >= 0; --i) {
    listaSugestoes[i].remove();
  }
  limpar.style.display = "none";
}

function buscaDiretor() {
  const diretorSelecao = diretor.value.toLowerCase();

  filmes.forEach(function (filme) {
    if (filme.direcao == diretorSelecao) {
      const sugestao = document.createElement("p");
      sugestao.innerText = filme.titulo + " - Disponível em: " + filme.stream;
      sugestao.classList.add("sugestoes");
      indicacao.appendChild(sugestao);
      limpar.style.display = "block";
    }
  });
  if (listaSugestoes.length < 1) {
    alert("Não foi possível encontrar nenhum filme");
  }
}
